stages:
  - build
  - test
  - deploy

build:gcc-4.9:
  stage: build
  image: bernddoser/docker-devel-cpp:ubuntu-16.04-gcc-4.9-gtest-1.8.0
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DGTEST_ROOT=/opt/googletest-1.8.0 ..
    - make -j
    
build:gcc-7:
  stage: build
  image: bernddoser/docker-devel-cpp:ubuntu-16.04-gcc-7-gtest-1.8.0
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DGTEST_ROOT=/opt/googletest-1.8.0 ..
    - make -j
    
build:clang-5:
  stage: build
  image: bernddoser/docker-devel-cpp:ubuntu-16.04-clang-5-gtest-1.8.0
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DGTEST_ROOT=/opt/googletest-1.8.0 ..
    - make -j
    
test:gcc-4.9:
  stage: test
  image: bernddoser/docker-devel-cpp:ubuntu-16.04-gcc-4.9-gtest-1.8.0
  dependencies:
    - build:gcc-4.9
  script:
    - cd build
    - make test
  cache:
    paths:
      - build
  artifacts:
    paths:
      - build

deploy:gcc-4.9:
  stage: deploy
  image: bernddoser/docker-devel-cpp:ubuntu-16.04-gcc-4.9-gtest-1.8.0
  dependencies:
    - test:gcc-4.9
  script:
    - cd build
    - make package
  artifacts:
    paths:
      - BlasBooster-*-Linux.tar.gz
  when: manual